defaults:
  - dataset: bag

wandb:
    project: gaussian_gen
    entity: summerkirakira
    name: Bag Test 5
    version: 0.1.3
    disabled: false

checkpointing:
  every_n_train_steps: 10000
  save_top_k: -1

output_path: outputs/bag

