defaults:
  - dataset: chair

wandb:
    project: gaussian_gen_chair_conditional
    entity: summerkirakira
    name: "4090-home"
    version: 0.1.3
    disabled: false

model:
  diffusion:
    use_kl: false
    min_snr: true

  unet:
    unconditional_gen: false
    precision: '32'

  diffusion_loss_weight: 1
  l1_loss_weight: 1
  lpips_loss_weight: 1

checkpointing:
  every_n_train_steps: 1000
  save_top_k: 5
  path: outputs/chair/checkpoints_test

trainer:
  max_steps: 300000
  learning_rate: 1e-4

inference:
  conditional_generation: false
  show_steps: true
  background_color: "black"

  condition:
    label_text: A purple sofa with 4 legs

load_from_checkpoint: /home/summerkirakira/Documents/Code/gaussianGen/outputs/last.ckpt
is_inference: false
use_fp16: false

