defaults:
  - dataset: chair

wandb:
    project: neo_gaussian_gen_chair_test
    entity: summerkirakira
    name: Test
    version: 0.1.3
    disabled: false

model:
  diffusion:
    use_kl: false
    min_snr: true

  diffusion_loss_weight: 1
  l1_loss_weight: 1
  lpips_loss_weight: 1

checkpointing:
  every_n_train_steps: 1000
  save_top_k: 5
  path: outputs/chair/checkpoints_test

trainer:
  max_steps: 300000
  learning_rate: 1e-4

load_from_checkpoint: /home/summerkirakira/Documents/Code/gaussianGen/outputs/chair/last.ckpt
is_inference: true

