defaults:
  - dataset: car

wandb:
    project: gaussian_gen
    entity: summerkirakira
    name: Car Test
    version: 0.1.3
    disabled: false

checkpointing:
  every_n_train_steps: 5000
  save_top_k: -1

output_path: outputs/car

